-------- DELETE 

-- delete left luggage recipt number 100001 
delete left_luggage_details ll where ll.ll_receipt_no = '100001';

-- delete left luggage recipt number 100002
delete left_luggage_details ll where ll.ll_receipt_no = '100002';

-- delete left luggage recipt number 100003
delete left_luggage_details ll where ll.ll_receipt_no = '100003';

-- delete left luggage bag number 100001-01
delete left_luggage_bag_details lb where lb.llbd_storage_tag_id = '100001-01';

-- delete left luggage bag number 100001-02
delete left_luggage_bag_details lb where lb.llbd_storage_tag_id = '100001-02';

-- delete left luggage bag number 100002-01
delete left_luggage_bag_details lb where lb.llbd_storage_tag_id = '100002-01';

-- delete left luggage bag number 100003-01
delete left_luggage_bag_details lb where lb.llbd_storage_tag_id = '100003-01';

COMMIT;

--------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------

------- INSERT

-- insert left luggage recipt number 100001
insert into left_luggage_details (LL_ID, LL_RECEIPT_NO, LL_AGENT_SHIFT_ID, LL_PAX_NAME, LL_ADDRESS, LL_PHONE_NO, LL_REMARKS, LL_PASSPORT_NO, LL_PAX_SIGN, LL_PAYMENT_AMOUNT, LL_PAYMENT_MODE, LL_PAYMENT_ACCEPTED_BY, LL_STATUS, LL_CREATED_DATE, LL_CREATED_BY, LL_UPDATED_DATE, LL_UPDATED_BY, LL_TOTAL_NUM_BAGS, LL_TOTAL_ACCRUED_CHARGES, LL_DISCOUNT, LL_NET_ACCRUED_CHARGES, LL_IS_SIGNED_FLAG, LL_CASHPAY, LL_POSPAY, LL_MCOPAY, LL_ESTIMATED_COLLECTION_DATE, LL_ESTMIATED_CHARGES, LL_ACTUAL_COLLECTION_DATE, LL_CUST_MAIL_ADDRESS, LL_OWNR_CARR_CODE, LL_PRNT_REQD, LL_COLLCT_SIGN, LL_COLLCT_EMAIL, LL_READY_COLLECT_FLAG, LL_COLLCT_SIGNED_FLAG)
values (10, '100001', null, 'LL TEST DEPOSIT 1', 'DUBAI', '9879879870', null, 'ABCDE12345', NULL, null, null, null, 'O', SYSDATE , 'S936386', SYSDATE , 'S936386', 3, 200, 0, 200, 'N', 0.00, 0.00, 0.00, SYSDATE + 1 , 200, NULL, 'CUSTOMER@TEST.COM', 'EK', null, NULL, 'COLLECTER@TEST.COM', 'N', 'N');

-- insert left luggage recipt number 100002
insert into left_luggage_details (LL_ID, LL_RECEIPT_NO, LL_AGENT_SHIFT_ID, LL_PAX_NAME, LL_ADDRESS, LL_PHONE_NO, LL_REMARKS, LL_PASSPORT_NO, LL_PAX_SIGN, LL_PAYMENT_AMOUNT, LL_PAYMENT_MODE, LL_PAYMENT_ACCEPTED_BY, LL_STATUS, LL_CREATED_DATE, LL_CREATED_BY, LL_UPDATED_DATE, LL_UPDATED_BY, LL_TOTAL_NUM_BAGS, LL_TOTAL_ACCRUED_CHARGES, LL_DISCOUNT, LL_NET_ACCRUED_CHARGES, LL_IS_SIGNED_FLAG, LL_CASHPAY, LL_POSPAY, LL_MCOPAY, LL_ESTIMATED_COLLECTION_DATE, LL_ESTMIATED_CHARGES, LL_ACTUAL_COLLECTION_DATE, LL_CUST_MAIL_ADDRESS, LL_OWNR_CARR_CODE, LL_PRNT_REQD, LL_COLLCT_SIGN, LL_COLLCT_EMAIL, LL_READY_COLLECT_FLAG, LL_COLLCT_SIGNED_FLAG)
values (11, '100002', null, 'LL TEST COLLECTION 2', 'DUBAI', '123456688', null, 'ABCDE54321', NULL, 200, null, null, 'D', SYSDATE , 'S936386', SYSDATE , 'S936386', 1, 200, 0, 200, 'N', 200.00, 0.00, 0.00, SYSDATE + 1 , 200, SYSDATE, 'CUSTOMER@TEST.COM', 'EK', null, NULL, 'COLLECTER@TEST.COM', 'Y', 'N');

-- insert left luggage recipt number 100002
insert into left_luggage_details (LL_ID, LL_RECEIPT_NO, LL_AGENT_SHIFT_ID, LL_PAX_NAME, LL_ADDRESS, LL_PHONE_NO, LL_REMARKS, LL_PASSPORT_NO, LL_PAX_SIGN, LL_PAYMENT_AMOUNT, LL_PAYMENT_MODE, LL_PAYMENT_ACCEPTED_BY, LL_STATUS, LL_CREATED_DATE, LL_CREATED_BY, LL_UPDATED_DATE, LL_UPDATED_BY, LL_TOTAL_NUM_BAGS, LL_TOTAL_ACCRUED_CHARGES, LL_DISCOUNT, LL_NET_ACCRUED_CHARGES, LL_IS_SIGNED_FLAG, LL_CASHPAY, LL_POSPAY, LL_MCOPAY, LL_ESTIMATED_COLLECTION_DATE, LL_ESTMIATED_CHARGES, LL_ACTUAL_COLLECTION_DATE, LL_CUST_MAIL_ADDRESS, LL_OWNR_CARR_CODE, LL_PRNT_REQD, LL_COLLCT_SIGN, LL_COLLCT_EMAIL, LL_READY_COLLECT_FLAG, LL_COLLCT_SIGNED_FLAG)
values (12, '100003', null, 'LL TEST COLLECTION 3', 'DUBAI', '123456789', null, 'ABCDE54345', NULL, 200, null, null, 'D', SYSDATE , 'S936386', SYSDATE , 'S936386', 1, 200, 0, 200, 'N', 200.00, 0.00, 0.00, SYSDATE + 1 , 200, SYSDATE, 'CUSTOMER@TEST.COM', 'EK', null, NULL, 'COLLECTER@TEST.COM', 'Y', 'N');


-- insert left luggage bag details 100001-01
insert into LEFT_LUGGAGE_BAG_DETAILS (LLBD_ID, LL_ID, LLBD_STORAGE_TAG_ID, LLBD_RACK_NO, LLBD_RACKED_BY, LLBD_RACK_DATE, LLBD_DEVICE_ID, LLBD_LOCATION_CODE, LLBD_BAG_TYPE, LLBD_FIRST_RACK_DATE, LLBD_COLLECT_DATE, LLBD_COLLECT_BY)
values (100, 10, '100001-01', NULL , NULL, NULL, '00:00:00:00:00:00', 'LEFTLUGG', 'VALUABLE', NULL,  null, null);

-- insert left luggage bag details 100001-02
insert into LEFT_LUGGAGE_BAG_DETAILS (LLBD_ID, LL_ID, LLBD_STORAGE_TAG_ID, LLBD_RACK_NO, LLBD_RACKED_BY, LLBD_RACK_DATE, LLBD_DEVICE_ID, LLBD_LOCATION_CODE, LLBD_BAG_TYPE, LLBD_FIRST_RACK_DATE, LLBD_COLLECT_DATE, LLBD_COLLECT_BY)
values (101, 10, '100001-02', NULL , NULL, NULL, '00:00:00:00:00:00', 'LEFTLUGG', 'STANDARD', NULL,  null, null);

-- insert left luggage bag details 100002-01
insert into LEFT_LUGGAGE_BAG_DETAILS (LLBD_ID, LL_ID, LLBD_STORAGE_TAG_ID, LLBD_RACK_NO, LLBD_RACKED_BY, LLBD_RACK_DATE, LLBD_DEVICE_ID, LLBD_LOCATION_CODE, LLBD_BAG_TYPE, LLBD_FIRST_RACK_DATE, LLBD_COLLECT_DATE, LLBD_COLLECT_BY)
values (102, 11, '100002-01', NULL , NULL, NULL, '00:00:00:00:00:00', 'LEFTLUGG', 'NON-STANDARD', NULL,  null, null);

-- insert left luggage bag details 100003-01
insert into LEFT_LUGGAGE_BAG_DETAILS (LLBD_ID, LL_ID, LLBD_STORAGE_TAG_ID, LLBD_RACK_NO, LLBD_RACKED_BY, LLBD_RACK_DATE, LLBD_DEVICE_ID, LLBD_LOCATION_CODE, LLBD_BAG_TYPE, LLBD_FIRST_RACK_DATE, LLBD_COLLECT_DATE, LLBD_COLLECT_BY)
values (103, 12, '100003-01', NULL , NULL, NULL, '00:00:00:00:00:00', 'LEFTLUGG', 'NON-STANDARD', NULL,  null, null);


COMMIT;
